// Fictional roster for Tara's class of 30 students — invented names, not
// sourced from any real student list. Sorted alphabetically by last name to
// match how a teacher's class roster is typically presented.
export const CLASS_ROSTER = [
  'Nora Bennett',
  'Silas Bennett',
  'Camila Brooks',
  'Jasper Brooks',
  'Amara Castillo',
  'Theo Castillo',
  'Ruby Delgado',
  'Malik Ellison',
  'Priya Fontaine',
  'Owen Fontaine',
  'Layla Garrison',
  'Diego Harmon',
  'Wren Harmon',
  'Beckett Ibarra',
  'Sienna Jaramillo',
  'Elias Kessler',
  'Nadia Kessler',
  'Marcus Linden',
  'Aviana Marsh',
  'Judah Novak',
  'Isla Ochoa',
  'Kian Ochoa',
  'Rosalind Pruitt',
  'Emmett Quintero',
  'Zara Reyes',
  'Beau Reyes',
  'Vivienne Solano',
  'Callum Tran',
  'Hazel Vance',
  'Ronan Whitfield',
]
