export const courses = [
  {
    id: 1,
    grade: 'Kindergarten',
    level: 'Early Elementary',
    title: 'Feelings & Friends',
    competency: 'Self-Awareness',
    color: '#2D7D78',
    lessons: 36,
  },
  {
    id: 2,
    grade: 'Grade 1',
    level: 'Early Elementary',
    title: 'My Emotions Matter',
    competency: 'Self-Awareness',
    color: '#2D7D78',
    lessons: 36,
  },
  {
    id: 3,
    grade: 'Grade 2',
    level: 'Early Elementary',
    title: 'Working Together',
    competency: 'Social Awareness',
    color: '#2D7D78',
    lessons: 36,
  },
  {
    id: 4,
    grade: 'Grade 3',
    level: 'Early Elementary',
    title: 'Understanding Our Emotions',
    competency: 'Self-Awareness',
    color: '#2D7D78',
    lessons: 36,
  },
  {
    id: 5,
    grade: 'Grade 4',
    level: 'Late Elementary',
    title: 'Self-Management in Action',
    competency: 'Self-Management',
    color: '#F5A623',
    lessons: 36,
  },
  {
    id: 6,
    grade: 'Grade 5',
    level: 'Late Elementary',
    title: 'Building Responsible Decisions',
    competency: 'Responsible Decision-Making',
    color: '#F5A623',
    lessons: 36,
  },
  {
    id: 7,
    grade: 'Grade 6',
    level: 'Middle School',
    title: 'Social Awareness & Empathy',
    competency: 'Social Awareness',
    color: '#7B5EA7',
    lessons: 36,
  },
  {
    id: 8,
    grade: 'Grade 7',
    level: 'Middle School',
    title: 'Relationship Skills',
    competency: 'Relationship Skills',
    color: '#7B5EA7',
    lessons: 36,
  },
  {
    id: 9,
    grade: 'Grade 8',
    level: 'Middle School',
    title: 'Goal-Directed Behavior',
    competency: 'Goal-Directed Behavior',
    color: '#7B5EA7',
    lessons: 36,
  },
  {
    id: 10,
    grade: 'Grade 9',
    level: 'High School',
    title: 'Identity & Resilience',
    competency: 'Self-Awareness',
    color: '#3B7DD8',
    lessons: 36,
  },
  {
    id: 11,
    grade: 'Grade 10',
    level: 'High School',
    title: 'Navigating Relationships',
    competency: 'Relationship Skills',
    color: '#3B7DD8',
    lessons: 36,
  },
  {
    id: 12,
    grade: 'Grade 11',
    level: 'High School',
    title: 'Responsible Decision-Making',
    competency: 'Responsible Decision-Making',
    color: '#3B7DD8',
    lessons: 36,
  },
  {
    id: 13,
    grade: 'Grade 12',
    level: 'High School',
    title: 'Leadership & Purpose',
    competency: 'Goal-Directed Behavior',
    color: '#3B7DD8',
    lessons: 36,
  },
]
