export const courses = [
  {
    id: 1,
    grade: 'Kindergarten',
    level: 'Early Elementary',
    title: 'Feelings & Friends',
    competency: 'Self-Awareness',
    color: '#2D7D78',
    lessons: 36,
  },
  {
    id: 2,
    grade: 'Grade 1',
    level: 'Early Elementary',
    title: 'My Emotions Matter',
    competency: 'Self-Awareness',
    color: '#2D7D78',
    lessons: 36,
  },
  {
    id: 3,
    grade: 'Grade 2',
    level: 'Early Elementary',
    title: 'Working Together',
    competency: 'Social Awareness',
    color: '#2D7D78',
    lessons: 36,
  },
  {
    id: 4,
    grade: 'Grade 3',
    level: 'Early Elementary',
    title: 'Understanding Our Emotions',
    competency: 'Self-Awareness',
    color: '#2D7D78',
    lessons: 36,
  },
  {
    id: 5,
    grade: 'Grade 4',
    level: 'Late Elementary',
    title: 'Self-Management in Action',
    competency: 'Self-Management',
    color: '#F5A623',
    lessons: 36,
  },
  {
    id: 6,
    grade: 'Grade 5',
    level: 'Late Elementary',
    title: 'Building Responsible Decisions',
    competency: 'Responsible Decision-Making',
    color: '#F5A623',
    lessons: 36,
  },
  {
    id: 7,
    grade: 'Grade 6',
    level: 'Middle School',
    title: 'Social Awareness & Empathy',
    competency: 'Social Awareness',
    color: '#7B5EA7',
    lessons: 36,
  },
  {
    id: 8,
    grade: 'Grade 7',
    level: 'Middle School',
    title: 'Relationship Skills',
    competency: 'Relationship Skills',
    color: '#7B5EA7',
    lessons: 36,
  },
  {
    id: 9,
    grade: 'Grade 8',
    level: 'Middle School',
    title: 'Goal-Directed Behavior',
    competency: 'Goal-Directed Behavior',
    color: '#7B5EA7',
    lessons: 36,
  },
  {
    id: 10,
    grade: 'Grade 9',
    level: 'High School',
    title: 'Identity & Resilience',
    competency: 'Self-Awareness',
    color: '#3B7DD8',
    lessons: 36,
  },
  {
    id: 11,
    grade: 'Grade 10',
    level: 'High School',
    title: 'Navigating Relationships',
    competency: 'Relationship Skills',
    color: '#3B7DD8',
    lessons: 36,
  },
  {
    id: 12,
    grade: 'Grade 11',
    level: 'High School',
    title: 'Responsible Decision-Making',
    competency: 'Responsible Decision-Making',
    color: '#3B7DD8',
    lessons: 36,
  },
  {
    id: 13,
    grade: 'Grade 12',
    level: 'High School',
    title: 'Leadership & Purpose',
    competency: 'Goal-Directed Behavior',
    color: '#3B7DD8',
    lessons: 36,
  },
]

// Adult Wellness — staff-facing wellness course
export const adultWellnessCourses = [
  {
    id: 201,
    grade: 'Adult Wellness',
    level: 'Staff & Educators',
    title: 'Adult Wellness',
    competency: 'Self-Awareness',
    color: '#2A7F8F',
    lessons: 7,
  },
]

// Tier 2 — targeted intervention courses, one per grade band
export const tier2Courses = [
  {
    id: 101,
    grade: 'Early Elementary',
    level: 'Tier 2',
    title: 'Tier 2 — Early Elementary',
    competency: 'Self-Awareness',
    color: '#FECD81',
    lessons: 18,
  },
  {
    id: 102,
    grade: 'Late Elementary',
    level: 'Tier 2',
    title: 'Tier 2 — Late Elementary',
    competency: 'Self-Management',
    color: '#FAA77D',
    lessons: 18,
  },
  {
    id: 103,
    grade: 'Middle School',
    level: 'Tier 2',
    title: 'Tier 2 — Middle School',
    competency: 'Relationship Skills',
    color: '#9ECB97',
    lessons: 18,
  },
  {
    id: 104,
    grade: 'High School',
    level: 'Tier 2',
    title: 'Tier 2 — High School',
    competency: 'Responsible Decision-Making',
    color: '#ABD4D7',
    lessons: 18,
  },
]
