export const courses = [
  {
    id: 1,
    image: '/courseImages/Lady_bug_toy_202604231144.jpeg',
    grade: 'Grade 3',
    level: 'Early Elementary',
    title: 'Understanding Our Emotions',
    competency: 'Self-Awareness',
    emoji: '🌱',
    color: '#2D7D78',
    lessons: 36,
  },
  {
    id: 2,
    image: '/courseImages/Butterfly_toy_illustration_202604231146.jpeg',
    grade: 'Grade 4',
    level: 'Late Elementary',
    title: 'Self-Management in Action',
    competency: 'Self-Management',
    emoji: '🦋',
    color: '#F5A623',
    lessons: 36,
  },
  {
    id: 3,
    image: '/courseImages/Bumble_bee_toy_202604231145.jpeg',
    grade: 'Grade 5',
    level: 'Late Elementary',
    title: 'Building Responsible Decisions',
    competency: 'Responsible Decision-Making',
    emoji: '🌟',
    color: '#E8653A',
    lessons: 36,
  },
  {
    id: 4,
    image: '/courseImages/Dinosaur_toy_illustration_202604231145.jpeg',
    grade: 'Grade 6',
    level: 'Middle School',
    title: 'Social Awareness & Empathy',
    competency: 'Social Awareness',
    emoji: '🤝',
    color: '#7B5EA7',
    lessons: 36,
  },
  {
    id: 5,
    image: '/courseImages/Lion_toy_illustration_202604231144.jpeg',
    grade: 'Grade 7',
    level: 'Middle School',
    title: 'Relationship Skills',
    competency: 'Relationship Skills',
    emoji: '💬',
    color: '#5B9E4D',
    lessons: 36,
  },
  {
    id: 6,
    image: '/courseImages/Hummingbird_toy_character_202604231145.jpeg',
    grade: 'Grade 8',
    level: 'Middle School',
    title: 'Goal-Directed Behavior',
    competency: 'Goal-Directed Behavior',
    emoji: '🎯',
    color: '#2A7F8F',
    lessons: 36,
  },
]
